# lua util系
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# ファイル検索
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/telescope')

  nnoremap <silent><C-p> <cmd>lua require('telescope.builtin').find_files()<cr>
  nnoremap <silent><S-f> <cmd>lua require('telescope.builtin').live_grep()<cr>
  nnoremap <silent><S-p> <cmd>lua require('telescope.builtin').buffers()<cr>

  nmap <silent><leader>ii  :e ~/.ignore<CR>
'''

# 背景透過
# FIXME: 最初に実行したいもので置いているが, 背景透過が起動が遅いので、colorschemeとして設定したい
[[plugins]]
repo = 'xiyaowong/transparent.nvim'
hook_add = '''
  lua require('plugins/transparent')
'''

################## UI

# icon
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# github theme
[[plugins]]
repo = 'projekt0n/github-nvim-theme'
on_event = ['BufReadPost','BufNewFile']
hook_add = '''
  autocmd ColorScheme * hi diffAdded      guifg=NONE guibg=#20303b 
  autocmd ColorScheme * hi diffChanged    guifg=NONE guibg=#1f2231 
  autocmd ColorScheme * hi diffRemoved    guifg=NONE guibg=#37222c 

  autocmd ColorScheme * hi DiffviewDiffAdd       guibg=#20303b 
  autocmd ColorScheme * hi DiffviewDiffChange    guibg=#1f2231 
  autocmd ColorScheme * hi DiffviewDiffDelete    guibg=#37222c 

  autocmd ColorScheme * hi StatusLine   gui=NONE guifg=white guibg=NONE 
  autocmd ColorScheme * hi StatusLineNC gui=NONE guifg=grey  guibg=NONE 
  " nvim-treeに依存しているので注意
  autocmd ColorScheme * highlight link NvimTreeNormal Normal

  colorscheme github_dark_colorblind
'''

# UI Component
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
hook_add = '''
  lua require('plugins/nui')
'''

# show trouble code
[[plugins]]
repo = 'folke/trouble.nvim'
depends = ['nvim-tree/nvim-web-devicons']
hook_add = '''
  lua require('plugins/trouble')
'''

################ LSP manager

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

# FIXME: dein_lazyに書きたい
# sql client
[[plugins]]
repo = 'tpope/vim-dadbod'

# sql client ui
[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
depends = ['tpope/vim-dadbod']
hook_add = '''
  source ~/.config/nvim/plugins/vim-dadbod-ui.vim
'''

################## AI

# Git ~でgit commandを提供する
[[plugins]]
repo = 'jackmort/chatgpt.nvim'
depends = [
  "MunifTanjim/nui.nvim",
  "nvim-lua/plenary.nvim",
  "folke/trouble.nvim",
  "nvim-telescope/telescope.nvim"
]
hook_add = '''
  echo "chatgpt.nvim is installed"
  lua require('plugins/chatgpt')
'''
